version: "3.8"

services:
  daemon:
    build:
      context: .
      dockerfile: Dockerfile
    image: homelytics-agent:latest
    container_name: homelytics-agent
    privileged: true
    network_mode: host
    command: ["--config", "/opt/homelytics/etc/config.yaml"]
    environment:
      - TAILSCALE_TAILNET=${TAILSCALE_TAILNET}
      - TAILSCALE_API_KEY=${TAILSCALE_API_KEY}
    volumes:
      - ./var/run:/opt/homelytics/run
      - ./files/config/app.yaml:/opt/homelytics/etc/config.yaml:ro
      - ./files/config/app.local.yaml:/opt/homelytics/etc/app.local.yaml:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - containerd-data:/opt/homelytics/lib/containerd
      - containerd-run:/run/containerd
    restart: unless-stopped

  cli:
    image: homelytics-agent:latest
    profiles:
      - cli
    depends_on:
      - daemon
    entrypoint: [""]
    command: ["homelytics-agent", "--config", "/opt/homelytics/etc/config.yaml", "status"]
    volumes:
      - ./var/run:/opt/homelytics/run
      - ./files/config/app.yaml:/opt/homelytics/etc/config.yaml:ro
      - ./files/config/app.local.yaml:/opt/homelytics/etc/app.local.yaml:ro

volumes:
  containerd-data:
  containerd-run:
